// ============================================================
// Shelly LoRa Gate Control - Virtual Sender
// ============================================================
// Sends an ON command through LoRa when a Virtual Component
// is activated.
//
// The Virtual Component is automatically reset to OFF after
// sending the command, allowing it to work as a momentary
// button.
//
// Compatible with the Gate Receiver script.
//
// Firmware: Shelly Gen3/Gen4 with LoRa Add-on
// ============================================================


// ============================================================
// CONFIGURATION
// ============================================================

const AES_KEY = 'YOUR_AES_KEY_HERE';

const LORA_ID = 100;
const VIRTUAL_COMPONENT = 'boolean:200';

const CHECKSUM_SIZE = 4;
const DEBUG = true;


// ============================================================
// INTERNAL STATE
// ============================================================

// Prevent the automatic reset to OFF from sending an OFF
// command through LoRa.
let resettingVirtualButton = false;


// ============================================================
// ENCRYPTION
// ============================================================

function fromHex(hex) {
    const arr = new ArrayBuffer(hex.length / 2);

    for (let i = 0; i < hex.length; i += 2) {
        arr[i / 2] = parseInt(hex.substr(i, 2), 16);
    }

    return arr;
}

function padRight(message, blockSize) {
    const paddingSize =
        (blockSize - message.length % blockSize) % blockSize;

    for (let i = 0; i < paddingSize; i++) {
        message += ' ';
    }

    return message;
}

function encryptMessage(message, keyHex) {
    message = message.trim();

    const formattedMessage = padRight(message, 16);
    const key = fromHex(keyHex);

    return AES.encrypt(
        formattedMessage,
        key,
        { mode: 'ECB' }
    );
}


// ============================================================
// CHECKSUM
// ============================================================

function generateChecksum(message) {
    let checksum = 0;

    for (let i = 0; i < message.length; i++) {
        checksum ^= message.charCodeAt(i);
    }

    let hexChecksum = checksum.toString(16);

    while (hexChecksum.length < CHECKSUM_SIZE) {
        hexChecksum = '0' + hexChecksum;
    }

    return hexChecksum.slice(-CHECKSUM_SIZE);
}


// ============================================================
// LORA TRANSMISSION
// ============================================================

function sendMessage(message) {
    const payload =
        generateChecksum(message) + message;

    const encryptedMessage =
        encryptMessage(payload, AES_KEY);

    Shelly.call(
        'Lora.SendBytes',
        {
            id: LORA_ID,
            data: btoa(encryptedMessage)
        },
        function (_, errorCode, errorMessage) {

            if (errorCode !== 0) {
                console.log(
                    '[LoRa TX] Error:',
                    errorCode,
                    errorMessage
                );
                return;
            }

            if (DEBUG) {
                console.log(
                    '[LoRa TX] Command sent:',
                    message
                );
            }
        }
    );
}


// ============================================================
// VIRTUAL COMPONENT
// ============================================================

Shelly.addStatusHandler(function (status) {

    if (
        status.component !== VIRTUAL_COMPONENT ||
        !status.delta ||
        typeof status.delta.value === 'undefined'
    ) {
        return;
    }

    // Ignore the OFF event generated by the automatic reset.
    if (resettingVirtualButton) {
        resettingVirtualButton = false;
        return;
    }

    // Only activation of the button sends a command.
    if (!status.delta.value) {
        return;
    }

    sendMessage('ON');

    // Reset the Virtual Component to OFF.
    resettingVirtualButton = true;

    Virtual
        .getHandle(VIRTUAL_COMPONENT)
        .setValue(false);

    if (DEBUG) {
        console.log(
            '[Virtual] Button reset to OFF'
        );
    }
});
